name: Django CI (Production)

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  PGPASSWORD: postgres
  SECRET_KEY: nonsense
  DATABASE_USER: alum
  DATABASE_PASS: password

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: project
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        sudo apt install -y python3-venv python3-dev libpq-dev nginx curl
        psql -h localhost -U postgres -c "CREATE USER alum WITH PASSWORD 'password';"
        psql -h localhost -U postgres -c "ALTER USER alum CREATEDB;"
        psql -h localhost -U postgres -c "ALTER ROLE alum SET client_encoding TO 'utf8';"
        psql -h localhost -U postgres -c "ALTER ROLE alum SET default_transaction_isolation TO 'read committed';"
        psql -h localhost -U postgres -c "ALTER ROLE alum SET timezone TO 'UTC';"
        psql -h localhost -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE project TO alum;"
        psql -h localhost -U postgres -d project -c "GRANT ALL ON schema public TO alum;"
        echo "SECRET_KEY='nonsense'" >> challenges/challenges/.env
        echo "DATABASE_USER='alum'" >> challenges/challenges/.env
        echo "DATABASE_PASS='password'" >> challenges/challenges/.env
        ls && cat challenges/challenges/.env
        python -m pip install --upgrade pip
        python -m pip install --upgrade pipenv
        python -m pip install --upgrade Django
        pipenv sync
        pipenv run makemigrations
        pipenv run migrate
    - name: Run Tests
      run: |
        pipenv run test
