# Generated by Django 5.0.1 on 2024-01-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed',
            field=models.ManyToManyField(blank=True, related_name='completed', to='challenges_app.challenges'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=None, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
