# Generated by Django 5.0.1 on 2024-01-29 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
