# Generated by Django 5.0.1 on 2024-02-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges_app", "0003_alter_challenges_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenges",
            name="author",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="challenges",
            name="course",
            field=models.CharField(default="CS50x", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="challenges",
            name="topics",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="challenges",
            name="week",
            field=models.IntegerField(default=0),
        ),
    ]
