# Generated by Django 5.0.1 on 2024-02-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges_app", "0004_challenges_author_challenges_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenges",
            name="fulltitle",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
