# Generated by Django 5.0.1 on 2024-02-01 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("challenges_app", "0005_challenges_fulltitle"),
    ]

    operations = [
        migrations.RenameField(
            model_name="challenges",
            old_name="fulltitle",
            new_name="full_title",
        ),
    ]
