# Generated by Django 5.0.1 on 2024-02-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges_app", "0006_rename_fulltitle_challenges_full_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenges",
            name="course",
        ),
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="CS50x", max_length=100, null=True)),
                (
                    "problems",
                    models.ManyToManyField(
                        null=True,
                        related_name="courses",
                        to="challenges_app.challenges",
                    ),
                ),
            ],
        ),
    ]
